/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Constants,
  ConstantsInterface,
} from "../../../contracts/libraries/Constants";

const _abi = [
  {
    inputs: [],
    name: "CHALLENGE_PERIOD_BUFFER",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEPOSIT_LOCKUP_PERIOD_SCALAR",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_CONFIRMATION_BLOCKS",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DEPOSIT_AMOUNT",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_OUTPUT_SATS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROOF_GEN_SCALING_FACTOR",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROTOCOL_FEE_BP",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCALED_PROOF_GEN_INTERCEPT",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCALED_PROOF_GEN_SLOPE",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601957610268908161001f823930815050f35b600080fdfe608080604052600436101561001357600080fd5b60003560e01c9081631ea30fef146101fe5750806320453a00146100bd57806339f09e9d146101c85780634a4f5fe61461019357806357c9b72c1461015e5780638634ec1b1461012957806397ea06a4146100f3578063a47f96cc146100bd5763ae099cfb1461008257600080fd5b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857602060405161012c8152f35b600080fd5b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b85760206040516103e88152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b8576020604051611c208152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857602060405160058152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857602060405160028152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857602060405160858152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857602060405161e3b38152f35b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100b857806107d160209252f3fea264697066735822122078ede47ce0ffd453115b4ddfaf9696e53c419b5333a1ba3cd3f08ce83098e39f64736f6c634300081c0033";

type ConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Constants__factory extends ContractFactory {
  constructor(...args: ConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Constants & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Constants__factory {
    return super.connect(runner) as Constants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConstantsInterface {
    return new Interface(_abi) as ConstantsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Constants {
    return new Contract(address, _abi, runner) as unknown as Constants;
  }
}
