version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rift-frontend
    restart: unless-stopped

    # Use host networking to access services running on the host
    network_mode: "host"

    environment:
      # Node environment
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

      # Add your environment variables here
      # QuickNode URLs
      - QUICKNODE_ETHEREUM_URL=${QUICKNODE_ETHEREUM_URL}
      - QUICKNODE_BASE_URL=${QUICKNODE_BASE_URL}

      # Public environment variables (available to browser)
      - NEXT_PUBLIC_OTC_SERVER_URL=${NEXT_PUBLIC_OTC_SERVER_URL:-http://localhost:8080}
      - NEXT_PUBLIC_IS_FRONTEND_PAUSED=${NEXT_PUBLIC_IS_FRONTEND_PAUSED:-false}

      # Add any other env vars your app needs
      # - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
      # - ANALYTICS_API_URL=${ANALYTICS_API_URL}

    # Health check
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
