/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISP1VerifierGateway } from "./ISP1VerifierGateway";
export type { ISP1VerifierGatewayErrors } from "./ISP1VerifierGatewayErrors";
export type { ISP1VerifierGatewayEvents } from "./ISP1VerifierGatewayEvents";
