/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface ISP1VerifierGatewayEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "RouteAdded(bytes4,address)": EventFragment;
    "RouteFrozen(bytes4,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RouteAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RouteFrozen"): EventFragment;
}

export interface RouteAddedEventObject {
  selector: string;
  verifier: string;
}
export type RouteAddedEvent = TypedEvent<
  [string, string],
  RouteAddedEventObject
>;

export type RouteAddedEventFilter = TypedEventFilter<RouteAddedEvent>;

export interface RouteFrozenEventObject {
  selector: string;
  verifier: string;
}
export type RouteFrozenEvent = TypedEvent<
  [string, string],
  RouteFrozenEventObject
>;

export type RouteFrozenEventFilter = TypedEventFilter<RouteFrozenEvent>;

export interface ISP1VerifierGatewayEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISP1VerifierGatewayEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "RouteAdded(bytes4,address)"(
      selector?: null,
      verifier?: null
    ): RouteAddedEventFilter;
    RouteAdded(selector?: null, verifier?: null): RouteAddedEventFilter;

    "RouteFrozen(bytes4,address)"(
      selector?: null,
      verifier?: null
    ): RouteFrozenEventFilter;
    RouteFrozen(selector?: null, verifier?: null): RouteFrozenEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
