/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface ISP1VerifierGatewayEventsInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "RouteAdded" | "RouteFrozen"): EventFragment;
}

export namespace RouteAddedEvent {
  export type InputTuple = [selector: BytesLike, verifier: AddressLike];
  export type OutputTuple = [selector: string, verifier: string];
  export interface OutputObject {
    selector: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteFrozenEvent {
  export type InputTuple = [selector: BytesLike, verifier: AddressLike];
  export type OutputTuple = [selector: string, verifier: string];
  export interface OutputObject {
    selector: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISP1VerifierGatewayEvents extends BaseContract {
  connect(runner?: ContractRunner | null): ISP1VerifierGatewayEvents;
  waitForDeployment(): Promise<this>;

  interface: ISP1VerifierGatewayEventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "RouteAdded"
  ): TypedContractEvent<
    RouteAddedEvent.InputTuple,
    RouteAddedEvent.OutputTuple,
    RouteAddedEvent.OutputObject
  >;
  getEvent(
    key: "RouteFrozen"
  ): TypedContractEvent<
    RouteFrozenEvent.InputTuple,
    RouteFrozenEvent.OutputTuple,
    RouteFrozenEvent.OutputObject
  >;

  filters: {
    "RouteAdded(bytes4,address)": TypedContractEvent<
      RouteAddedEvent.InputTuple,
      RouteAddedEvent.OutputTuple,
      RouteAddedEvent.OutputObject
    >;
    RouteAdded: TypedContractEvent<
      RouteAddedEvent.InputTuple,
      RouteAddedEvent.OutputTuple,
      RouteAddedEvent.OutputObject
    >;

    "RouteFrozen(bytes4,address)": TypedContractEvent<
      RouteFrozenEvent.InputTuple,
      RouteFrozenEvent.OutputTuple,
      RouteFrozenEvent.OutputObject
    >;
    RouteFrozen: TypedContractEvent<
      RouteFrozenEvent.InputTuple,
      RouteFrozenEvent.OutputTuple,
      RouteFrozenEvent.OutputObject
    >;
  };
}
