/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAllowanceTransfer } from "./IAllowanceTransfer";
export type { IDAIPermit } from "./IDAIPermit";
export type { IEIP712 } from "./IEIP712";
export type { IERC1271 } from "./IERC1271";
export type { IPermit2 } from "./IPermit2";
export type { ISignatureTransfer } from "./ISignatureTransfer";
