/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISP1VerifierGatewayEvents,
  ISP1VerifierGatewayEventsInterface,
} from "../../../../contracts/sp1/ISP1VerifierGateway.sol/ISP1VerifierGatewayEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "RouteAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        indexed: false,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "RouteFrozen",
    type: "event",
  },
] as const;

export class ISP1VerifierGatewayEvents__factory {
  static readonly abi = _abi;
  static createInterface(): ISP1VerifierGatewayEventsInterface {
    return new utils.Interface(_abi) as ISP1VerifierGatewayEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISP1VerifierGatewayEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISP1VerifierGatewayEvents;
  }
}
