/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISP1Verifier } from "./ISP1Verifier";
export type { ISP1VerifierWithHash } from "./ISP1VerifierWithHash";
