/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface ISP1VerifierWithHashInterface extends utils.Interface {
  functions: {
    "VERIFIER_HASH()": FunctionFragment;
    "verifyProof(bytes32,bytes,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "VERIFIER_HASH" | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "VERIFIER_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "VERIFIER_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISP1VerifierWithHash extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISP1VerifierWithHashInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VERIFIER_HASH(overrides?: CallOverrides): Promise<[string]>;

    verifyProof(
      programVKey: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  VERIFIER_HASH(overrides?: CallOverrides): Promise<string>;

  verifyProof(
    programVKey: BytesLike,
    publicValues: BytesLike,
    proofBytes: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    VERIFIER_HASH(overrides?: CallOverrides): Promise<string>;

    verifyProof(
      programVKey: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    VERIFIER_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    verifyProof(
      programVKey: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VERIFIER_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifyProof(
      programVKey: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
