/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type BlockLeafStruct = {
    blockHash: BytesLike;
    height: BigNumberish;
    cumulativeChainwork: BigNumberish;
  };

  export type BlockLeafStructOutput = [
    blockHash: string,
    height: bigint,
    cumulativeChainwork: bigint
  ] & { blockHash: string; height: bigint; cumulativeChainwork: bigint };

  export type DepositLiquidityParamsStruct = {
    depositOwnerAddress: AddressLike;
    specifiedPayoutAddress: AddressLike;
    depositAmount: BigNumberish;
    expectedSats: BigNumberish;
    btcPayoutScriptPubKey: BytesLike;
    depositSalt: BytesLike;
    confirmationBlocks: BigNumberish;
    safeBlockLeaf: Types.BlockLeafStruct;
    safeBlockSiblings: BytesLike[];
    safeBlockPeaks: BytesLike[];
  };

  export type DepositLiquidityParamsStructOutput = [
    depositOwnerAddress: string,
    specifiedPayoutAddress: string,
    depositAmount: bigint,
    expectedSats: bigint,
    btcPayoutScriptPubKey: string,
    depositSalt: string,
    confirmationBlocks: bigint,
    safeBlockLeaf: Types.BlockLeafStructOutput,
    safeBlockSiblings: string[],
    safeBlockPeaks: string[]
  ] & {
    depositOwnerAddress: string;
    specifiedPayoutAddress: string;
    depositAmount: bigint;
    expectedSats: bigint;
    btcPayoutScriptPubKey: string;
    depositSalt: string;
    confirmationBlocks: bigint;
    safeBlockLeaf: Types.BlockLeafStructOutput;
    safeBlockSiblings: string[];
    safeBlockPeaks: string[];
  };

  export type BundlerResultStruct = {
    initialCbBTCBalance: BigNumberish;
    finalCbBTCBalance: BigNumberish;
    cbBTCReceived: BigNumberish;
  };

  export type BundlerResultStructOutput = [
    initialCbBTCBalance: bigint,
    finalCbBTCBalance: bigint,
    cbBTCReceived: bigint
  ] & {
    initialCbBTCBalance: bigint;
    finalCbBTCBalance: bigint;
    cbBTCReceived: bigint;
  };
}

export declare namespace ISignatureTransfer {
  export type TokenPermissionsStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type TokenPermissionsStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type PermitTransferFromStruct = {
    permitted: ISignatureTransfer.TokenPermissionsStruct;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type PermitTransferFromStructOutput = [
    permitted: ISignatureTransfer.TokenPermissionsStructOutput,
    nonce: bigint,
    deadline: bigint
  ] & {
    permitted: ISignatureTransfer.TokenPermissionsStructOutput;
    nonce: bigint;
    deadline: bigint;
  };
}

export interface IBundlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cbBTC"
      | "executeSwapAndDeposit"
      | "permit2"
      | "riftExchange"
      | "swapRouter"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "cbBTC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeSwapAndDeposit",
    values: [
      BigNumberish,
      BytesLike,
      Types.DepositLiquidityParamsStruct,
      AddressLike,
      ISignatureTransfer.PermitTransferFromStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "riftExchange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cbBTC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSwapAndDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riftExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
}

export interface IBundler extends BaseContract {
  connect(runner?: ContractRunner | null): IBundler;
  waitForDeployment(): Promise<this>;

  interface: IBundlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cbBTC: TypedContractMethod<[], [string], "view">;

  executeSwapAndDeposit: TypedContractMethod<
    [
      amountIn: BigNumberish,
      swapCalldata: BytesLike,
      params: Types.DepositLiquidityParamsStruct,
      owner: AddressLike,
      permit: ISignatureTransfer.PermitTransferFromStruct,
      signature: BytesLike
    ],
    [Types.BundlerResultStructOutput],
    "payable"
  >;

  permit2: TypedContractMethod<[], [string], "view">;

  riftExchange: TypedContractMethod<[], [string], "view">;

  swapRouter: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cbBTC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeSwapAndDeposit"
  ): TypedContractMethod<
    [
      amountIn: BigNumberish,
      swapCalldata: BytesLike,
      params: Types.DepositLiquidityParamsStruct,
      owner: AddressLike,
      permit: ISignatureTransfer.PermitTransferFromStruct,
      signature: BytesLike
    ],
    [Types.BundlerResultStructOutput],
    "payable"
  >;
  getFunction(
    nameOrSignature: "permit2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riftExchange"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
